### ISSUE TITLE
encoding/decoding errors in loadJSON()

### ISSUE THREAD

**Issue by abubelinha** [PolBaladas/torsimany#10]
I installed the program with `pip install torsimany`. 

Then I downloaded the example files, but I get two kinds of error when trying to convert them to markdown:

### Error type 1: `AttributeError: 'str' object has no attribute 'decode'`
This happens with files `products.json`, `Traffic_Incidents_microsoft.json` or any other json file of my own ... except `loklak.json` (see error 2). 

**command:**
`c:\>C:\Users\Abu\AppData\Local\Programs\Python\Python38\scripts\torsimany c:\temp\products.json
`

**output:**
```
Traceback (most recent call last):
  File "c:\users\abu\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\abu\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\abu\AppData\Local\Programs\Python\Python38\scripts\torsimany.exe\__main__.py", line 7, in <module>
  File "c:\users\abu\appdata\local\programs\python\python38\lib\site-packages\torsimany\torsimany.py", line 73, in main
    justdoit(input_file, output_file)
  File "c:\users\abu\appdata\local\programs\python\python38\lib\site-packages\torsimany\torsimany.py", line 60, in justdoit
    json_data = loadJSON(input_file)
  File "c:\users\abu\appdata\local\programs\python\python38\lib\site-packages\torsimany\torsimany.py", line 11, in loadJSON
    data = f.read().decode('ascii', 'ignore')
AttributeError: 'str' object has no attribute 'decode'
```
Looking to that line 11
`data = f.read().decode('ascii', 'ignore')`
... as I am using Python 3.8, I think the might be related to [this](https://stackoverflow.com/questions/28583565/str-object-has-no-attribute-decode-python-3-error/28583969#28583969)

### Error type 2: `UnicodeDecodeError: 'charmap' codec can't decode byte`
This error only happens when trying to convert the `loklak.json` file (also mentioned in #9): 
https://raw.githubusercontent.com/PolBaladas/torsimany/master/Examples/loklak.json

**command:**
`c:\>C:\Users\Abu\AppData\Local\Programs\Python\Python38\scripts\torsimany c:\temp\loklak.json
`

**output:**
```
Traceback (most recent call last):
  File "c:\users\abu\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\abu\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\abu\AppData\Local\Programs\Python\Python38\scripts\torsimany.exe\__main__.py", line 7, in <module>
  File "c:\users\abu\appdata\local\programs\python\python38\lib\site-packages\torsimany\torsimany.py", line 73, in main
    justdoit(input_file, output_file)
  File "c:\users\abu\appdata\local\programs\python\python38\lib\site-packages\torsimany\torsimany.py", line 60, in justdoit
    json_data = loadJSON(input_file)
  File "c:\users\abu\appdata\local\programs\python\python38\lib\site-packages\torsimany\torsimany.py", line 11, in loadJSON
    data = f.read().decode('ascii', 'ignore')
  File "c:\users\abu\appdata\local\programs\python\python38\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 7446: character maps to <undefined>
```
___________________

**My system:** 
Windows 7
Python 3.8

**Comment by anton-b** [comment]
data = f.read().decode('ascii', 'ignore')
           ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?

having the same issue 

Python 3.11.11

torsimany                                1.0

**Comment by catsquawk** [comment]
Not exactly a techie, but same thing here.

```
PS C:\Users\user> torsimany notes.json
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\user\AppData\Roaming\Python\Python311\Scripts\torsimany.exe\__main__.py", line 7, in <module>
  File "C:\Users\user\AppData\Roaming\Python\Python311\site-packages\torsimany\torsimany.py", line 73, in main
    justdoit(input_file, output_file)
  File "C:\Users\user\AppData\Roaming\Python\Python311\site-packages\torsimany\torsimany.py", line 60, in justdoit
    json_data = loadJSON(input_file)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python311\site-packages\torsimany\torsimany.py", line 11, in loadJSON
    data = f.read().decode('ascii', 'ignore')
           ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
```

Windows 10, Python 3.11.0
